version: '3'
services:
  wildfly:
    build: ./wildfly
    tty: true
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.m2:/root/.m2
      - ..:/workspace
