name: Selenium Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: テスト環境のビルドと実行
        run: |-
          docker compose -f selenium/docker-compose.yaml build
          docker compose -f selenium/docker-compose.yaml up -d
      - name: Chromeテスト結果確認
        if: ${{ always() }}
        run: |-
          docker compose -f selenium/docker-compose.yaml logs test-runner-for-chrome
          EXITCODE=$(docker compose -f selenium/docker-compose.yaml ps -a --format json test-runner-for-chrome | jq '.[0].ExitCode')
          if [ $EXITCODE -ne 0 ]; then exit 1; fi
      - name: Edgeテスト結果確認
        if: ${{ always() }}
        run: |-
          docker compose -f selenium/docker-compose.yaml logs test-runner-for-edge
          EXITCODE=$(docker compose -f selenium/docker-compose.yaml ps -a --format json test-runner-for-edge | jq '.[0].ExitCode')
          if [ $EXITCODE -ne 0 ]; then exit 1; fi
      - name: Firefoxテスト結果確認
        if: ${{ always() }}
        run: |-
          docker compose -f selenium/docker-compose.yaml logs test-runner-for-firefox
          EXITCODE=$(docker compose -f selenium/docker-compose.yaml ps -a --format json test-runner-for-firefox | jq '.[0].ExitCode')
          if [ $EXITCODE -ne 0 ]; then exit 1; fi
      - name: エビデンスを圧縮
        if: ${{ always() }}
        run: >-
          zip -r results.zip selenium/test-runner/results/
      - name: Upload Evidence
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: evidences
          path: results.zip
